version: "3"
services:
  db:
    build: .
    image: mongo:noble
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  be:
    build:
      context: ./be
      dockerfile: "dev.Dockerfile"
    volumes:
      - ./be:/app/be
      - /app/be/node_modules
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - CORS=1
      - DEBUG=express:*
      - DB=mongodb://db:27017/mern
      - react_app_url=http://localhost/
    command: "nodemon -L server.js"
    depends_on:
      - db

  fe:
    build:
      context: ./fe
      dockerfile: "dev.Dockerfile"
    restart: always
    volumes:
      - ./fe:/app/fe
      - /app/fe/node_modules
    ports:
      - "80:80"
    environment:
      - PORT=80
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://127.0.0.1:3000
    depends_on:
      - be
    command: "npm run start"

volumes:
  data:
