version: "3"
services:
  # nginx:
  #   build: .
  #   ports:
  #     - "80:80"
  #     - "3000:3000"
  #     - "4200:4200"
  be:
    build:
      context: .
      # context: ./be
      # dockerfile: "dev.Dockerfile"
    volumes:
      - ./be:/app/
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - CORS=1
      - DEBUG=express:*
      - db=mongodb://103.77.242.64:27017/mern
      - react_app_url=http://localhost/

    command: "nodemon -L server.js"

  fe:
    build:
      context: .
      # context: ./fe
      # dockerfile: "dev.Dockerfile"
    restart: always
    volumes:
      - ./fe:/app/fe
      - /app/fe/node_modules
    ports:
      - "80:80"
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://127.0.0.1:3000
      - PORT=80

    command: "npm run --prefix fe start"
