version: "3"
services:
  be:
    container_name: ${NAME_BE}
    build:
      context: ./be/
      dockerfile: "Dockerfile"
    restart: always
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      - DB=${DB}
      - NAME_BE = ${NAME_BE}
  fe:
    container_name: ${NAME_FE}
    build:
      context: ./fe/
      dockerfile: "Dockerfile"
    restart: always
    ports:
      - 80:80
    environment:
      - NAME_FE=${NAME_FE}
    #   default:
    #     # Use a custom driver
    #     name: net
    #     driver: custom-driver-1

    # docker compose -p app up
    # docker compose -p app up --build
    #llll
