version: "3"
services:
  be:
    container_name: be
    build:
      context: ./be/
      dockerfile: "Dockerfile"
    restart: always
    ports:
      - 3000:3000
  fe:
    container_name: fe
    build:
      context: ./fe/
      dockerfile: "Dockerfile"
    restart: always
    ports:
      - 80:80

# docker compose -p app up
# docker compose -p app up --build
